version: '3.7'

networks:
  crm:
    external: true

services:
  message:
    image: message:latest
    container_name: messages
    ports:
      - "9005:9005"
    environment:
      - CONFIG_SERVER_LOGIN=user
      - CONFIG_SERVER_PASSWORD=user
      - SPRING_PROFILES_ACTIVE=default
      - CONFIG_SERVER_URI=http://user:user@settings:8888
      - KAFKA_URL=kafka:9092
      - UDB_PASSWORD=1904
      - UDB_URL=jdbc:postgresql://postgres:5432/users
      - UDB_USERNAME=users_reader
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
      - MAIL_ACCESS_TOKEN=nzzfyualtdfimbwj
      - MAIL_ADDRESS=utility.mailer.com@gmail.com
      - TELEGRAM_BOT_USERNAME=CRMManagementBot
      - TELEGRAM_BOT_TOKEN=6340890323:AAGFtYCCJwkA8Ghkc990Dyfc3KjRNXgnlZQ
    networks:
      - crm